### ISSUE TITLE
Precommit after the original prettier formating

### ISSUE THREAD

**Issue by defusioner** [nrwl/precise-commits#5]
Hey there!
We are about to inject prettier to our project, so we looked for manual/automatic ways of its usage.

When I run Prettier manually on a .js file, and then commit it using precommit (thanks for the fix in #2 ), I get the same error as in that ticket:
```
 SyntaxError: Unexpected token (5:9)
  4 |         // code
> 5 |       } else {
    |         ^
  6 |         // code
  7 |       }

```

However, if I don't call prettier manually, there is no problem.

**Comment by JamesHenry** [comment]
Hi @defusioner, we will definitely need more information here.

The output you have pasted does not contain any stack trace so it is impossible to tell what is happening. I don't think your issue is related to #2 from your description.

The best way to help us dig into the issue you are facing is by providing a minimal reproduction of the issue.

**Comment by defusioner** [comment]
Seems that this is no longed reproducible in 1.10.1 @JamesHenry

**Comment by JamesHenry** [comment]
Thanks for letting me know!
